BeerScore\BeerBundle\Entity\Review:
    type: entity
    table: null
    repositoryClass: BeerScore\BeerBundle\Repository\ReviewRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        content:
            type: text
        userName:
            type: string
            length: 255
            column: user_name
        aromaScore:
            type: smallint
            column: aroma_score
        appearanceScore:
            type: smallint
            column: appearance_score
        tasteScore:
            type: smallint
            column: taste_score
        palateScore:
            type: smallint
            column: palate_score
        overallScore:
            type: decimal
            precision: '7'
            scale: '5'
            nullable: true
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at
    manyToOne:
        beer:
            targetEntity: Beer
            inversedBy: reviews
    lifecycleCallbacks:
        prePersist: [ updatedTimestamps ]