beer_index:
    path:     /
    defaults: { _controller: "BeerScoreBeerBundle:Beer:index" }
    methods:  GET
beer_score_beer:
    resource: "@BeerScoreBeerBundle/Resources/config/routing/beer.yml"
    prefix:   /beer
beer_score_review:
    resource: "@BeerScoreBeerBundle/Resources/config/routing/review.yml"
    prefix:   /review

