<?php

namespace BeerScore\Beer\Infrastructure\Persistance\Repository\Doctrine;

use BeerScore\Beer\Domain\Model\BeerRepository as BeerRepositoryInterface;
use BeerScore\Beer\Domain\Model\Beer;
use \Doctrine\ORM\EntityRepository;

/**
 * BeerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BeerRepository extends EntityRepository implements BeerRepositoryInterface
{

    /**
     * @param int $id
     * @return null|object
     */
    public function findById(int $id)
    {
        return $this->find($id);
    }

    /**
     * @param null $orderBy
     * @return array
     */
    public function findAll($orderBy = null): array
    {
        return $this->findBy(
            array(),
            isset($orderBy) ? $orderBy : array()
        );
    }

    /**
     * @param \BeerScore\Beer\Domain\Model\Beer $beer
     */
    public function save(Beer $beer)
    {
        $entityManager = $this->getEntityManager();
        $entityManager->persist($beer);
        $entityManager->flush($beer);
    }
}
