<?php

namespace BeerScore\Beer\Infrastructure\Persistance\Repository\Doctrine;

use BeerScore\Beer\Domain\Model\BeerRepository as BeerRepositoryInterface;
use BeerScore\Beer\Domain\Model\Beer;
use \Doctrine\ORM\EntityRepository;

/**
 * BeerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BeerRepository extends EntityRepository implements BeerRepositoryInterface
{

    /**
     * Returns entity with given id
     *
     * @param int $id
     * @return null|Beer
     */
    public function findById(int $id): ?Beer
    {
        return $this->find($id);
    }

    /**
     * Returns all entities
     *
     * @param array $orderBy
     * @return array
     */
    public function findAll(array $orderBy = null): array
    {
        return $this->findBy(
            array(),
            isset($orderBy) ? $orderBy : array()
        );
    }

    /**
     * Persists a beer
     *
     * @param Beer $beer
     * @return Beer
     */
    public function save(Beer $beer): Beer
    {
        $entityManager = $this->getEntityManager();
        $id = $beer->getId();
        if (!isset($id)) {
            $entityManager->persist($beer);
        }
        $entityManager->flush($beer);

        return $beer;
    }

    /**
     * Removes a beer
     *
     * @param Beer $beer
     */
    public function remove(Beer $beer)
    {
        $entityManager = $this->getEntityManager();
        $entityManager->remove($beer);
        $entityManager->flush($beer);
    }
}
